---
title: "forecast"
author: "Helen Yezerets"
date: "February 25, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Load econ5 data
```{r}
data(econ5, package="astsa")
```
##Add new forcast values to econ5$gnp with append

```{r}
library(forecast)

inputData = na.omit(econ5$gnp)
startDate = min(time(econ5.ts))

timeSeries = ts(inputData, start = startDate, deltat = 1/52)

#timeSeriesForecast = forecast(timeSeries, h = 4, level = 95, find.frequency = TRUE)
timeSeriesForecast = forecast(timeSeries,  h = 4, level = 95)
append(inputData, 
       timeSeriesForecast$mean)

```
##cluster
```{r}
minPts<- 5
epsilon<-0.5 
GNP=econ5$gnp
GovInv=econ5$govinv

library(dbscan)

data <- cbind(GNP, GovInv)

db <- dbscan(data, 
             eps = epsilon, 
             minPts = minPts
             )$cluster

db[db > 0] <- 'Yes'
db[db == 0] <- 'No'

db

```

##cluster
```{r}
econ5.cl<-as.matrix(econ5[,1:5])
kNNdistplot(econ5.cl)
abline(h=.5, col = "red", lty=2)
db <- dbscan(econ5.cl, 
             eps = .5, 
             minPts = 5
             )

db
pairs(econ5.cl, col = db$cluster + 1L)
```

```{r}

## use precomputed frNN
fr <- frNN(econ5, eps = .5)
dbscan(fr, minPts = 5)

```

```{r}
## example data from fpc
set.seed(665544)
n <- 100
x <- cbind(
  x = runif(10, 0, 10) + rnorm(n, sd = 0.2),
  y = runif(10, 0, 10) + rnorm(n, sd = 0.2)
  )

res <- dbscan(x, eps = .3, minPts = 3)
res
```

```{r}

## plot clusters and add noise (cluster 0) as crosses.
plot(x, col=res$cluster)
points(x[res$cluster==0,], pch = 3, col = "grey")

hullplot(x, res)
```


```{r}

## predict cluster membership for new data points
## (Note: 0 means it is predicted as noise)
newdata <- x[1:5,] + rnorm(10, 0, .2)
predict(res, newdata, data = x)

```

```{r}

## compare speed against fpc version (if microbenchmark is installed)
## Note: we use dbscan::dbscan to make sure that we do now run the
## implementation in fpc.
## Not run: 
if (requireNamespace("fpc", quietly = TRUE) &&
    requireNamespace("microbenchmark", quietly = TRUE)) {
  t_dbscan <- microbenchmark::microbenchmark(
    dbscan::dbscan(x, .3, 3), times = 10, unit = "ms")
  t_dbscan_linear <- microbenchmark::microbenchmark(
    dbscan::dbscan(x, .3, 3, search = "linear"), times = 10, unit = "ms")
  t_dbscan_dist <- microbenchmark::microbenchmark(
    dbscan::dbscan(x, .3, 3, search = "dist"), times = 10, unit = "ms")
  t_fpc <- microbenchmark::microbenchmark(
    fpc::dbscan(x, .3, 3), times = 10, unit = "ms")

  r <- rbind(t_fpc, t_dbscan_dist, t_dbscan_linear, t_dbscan)
  r
  
  boxplot(r,
    names = c('fpc', 'dbscan (dist)', 'dbscan (linear)', 'dbscan (kdtree)'),
    main = "Runtime comparison in ms")

  ## speedup of the kd-tree-based version compared to the fpc implementation
  median(t_fpc$time) / median(t_dbscan$time)
}
## End(Not run)

```